# Generated by Django 5.2 on 2025-07-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Room', 'Room')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('furnished', models.BooleanField(default=False)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='property_apps.property')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
